---
functional:
  - Должен присутсвовать чат, где пользователи могут общаться друг с другом
  - Должна быть возможность создать игру
  - Должна присутствовать возможность выбрать уровень, тип игры, время игры, а также задачу.
  - Возможность поиграть в codebattle с другом.
  - Возможность создать турнир
  - Возможность сыграть в codebattle с ботом или случайным соперником
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров - Сhrome, Opera, Yandex, Mozilla Firefox, Edge
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Должна присутсвовать авторизация и регистрация пользователя.
  
